baseURL = "https://stoic-bell-8b8326.netlify.com"
languageCode = "en-us"
title = "IoT Field Service Event"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/


# Site Params
[params]
    home = "Pylades IOT Experience"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "/images/slider2.jpg"
        heading = "Meld u aan voor de Pylades Connect Field Service Experience"
        description = "quasi dolores numquam dolor vero ex, tempora commodi repellendus quod laborum."
        btn     = true
        btnText = "AANMELDEN"
        btnURL  = "https://forms.office.com/Pages/ResponsePage.aspx?id=C7l6RXDQ0EGg974_IsqZZlPpQAwKJnNEjMhakYqqkXRURU5BNlkwUlVKUzA0MFJLNU5CSUtHSkZHUy4u"
        [[params.banner.flipText]]
            title   = "Smart Industry"
        [[params.banner.flipText]]
            title   = "Pro Active Field Service"
        [[params.banner.flipText]]
            title   = "Microsoft Dynamics 365"
        [[params.banner.flipText]]
            title   = "Predictive IoT"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "WACHT NIET LANGER"
        content = "Meld u hier aan"
        btnText = "AANMELDEN"
        btnURL  = "https://forms.office.com/Pages/ResponsePage.aspx?id=C7l6RXDQ0EGg974_IsqZZlPpQAwKJnNEjMhakYqqkXRURU5BNlkwUlVKUzA0MFJLNU5CSUtHSkZHUy4u"