baseURL = "https://stoic-bell-8b8326.netlify.com"
languageCode = "en-us"
title = "Connected Field Service Executive Event"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus

# Site Params
[params]
    home = "Home"
    logo = "/images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "/images/slider2.jpg"
        heading = " Connected Field Service Executive Event"
        description = "Een inspirerend, interactief event op locatie voor Technisch Dienstverleners"
        btn     = true
        btnText = "AANMELDEN"
        btnURL  = "/aanmelden"
        [[params.banner.flipText]]
            title   = "Inspirerend"
        [[params.banner.flipText]]
            title   = "Interactief"
        [[params.banner.flipText]]
            title   = "Educatief"
        [[params.banner.flipText]]
            title   = "Netwerken"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = ""
        url     = ""
        weight  = 2
    [[menu.nav]]
        name    = "Aanmelden"
        url     = "/aanmelden"
        weight  = 6

 # Homepage About Section
    [params.about]
        enable  = true
        title   = "Het Pylades en Microsoft Field Service Event"
        content = "Showcase toekomst van Field Service, A.I en IoT"
        image   = "images/about/Innovate-With-Proactive_767x367.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "Meld u aan en ontvang de gratis Field Service Factsheet"
        content = "Download Nu"
        btnText = "Download"
        btnURL  = "/contact"

