baseURL = "https://stoic-bell-8b8326.netlify.com"
languageCode = "en-us"
title = "Pylades IOT Experience"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/


# Site Params
[params]
    home = "Pylades IOT Experience"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "/images/slider.jpg"
        heading = "Schrijf je in voor de Pylades IOT Experience"
        description = "Rondleiding door het nieuwe kantoor van Microsoft en een workshop van Dynamics 365 Field Service gericht op Technisch Dienstverleners"
        btn     = true
        btnText = "INSCHRIJVEN"
        btnURL  = "https://forms.office.com/Pages/ResponsePage.aspx?id=C7l6RXDQ0EGg974_IsqZZlPpQAwKJnNEjMhakYqqkXRURU5BNlkwUlVKUzA0MFJLNU5CSUtHSkZHUy4u"
        [[params.banner.flipText]]
            title   = "INTERACTIEF"
        [[params.banner.flipText]]
            title   = "MODERN WORKPLACE"
        [[params.banner.flipText]]
            title   = "DIGITAL TRANSFORMATION"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "WACHT NIET LANGER"
        content = "Schrijf je hier in"
        btnText = "Inschrijven"
        btnURL  = "https://forms.office.com/Pages/ResponsePage.aspx?id=C7l6RXDQ0EGg974_IsqZZlPpQAwKJnNEjMhakYqqkXRURU5BNlkwUlVKUzA0MFJLNU5CSUtHSkZHUy4u"