baseURL = "https://fieldservice.digital"
languageCode = "nl"
title = "Pylades Connected Field Service Executive Event"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus

# Site Params
[params]
    home = "/"
    logo = "/images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "/images/slider2.jpg"
        heading = "Pylades Field Service Executive Event"
        description = "Een inspirerend event voor toekomstgerichte, innovatieve Technisch Dienstverleners"
        btn     = true
        btnText = "AANMELDEN"
        btnURL  = "/contact"
        [[params.banner.flipText]]
            title   = "Inspirerend"
        [[params.banner.flipText]]
            title   = "Interactief"
        [[params.banner.flipText]]
            title   = "Educatief"
        [[params.banner.flipText]]
            title   = "Exclusief"

# Site Menus

 # Homepage About Section
    [params.about]
        enable  = true
        title   = "Pylades Connected Field Service Executive Event"
        content = "Pylades organiseert in samenwerking met Microsoft een rondleiding en interactieve Need To Know Sessie in het splinternieuwe, IoT enabled Microsoft kantoor te Schiphol"
        image   = "images/about/Innovate-With-Proactive_767x367.png"


    # Call to Action
    [params.cta]
        enable  = true
        title   = "Meld u aan om kans te maken op deelname aan dit event"
        content = "Aanmelden"
        btnText = "Aanmelden"
        btnURL  = "/contact"

