baseURL = "https://fieldservice.digital"
languageCode = "nl"
title = "Pylades Connected Field Service Executive Event"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus

# Site Params
[params]
    home = "/"
    logo = "/images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "/images/background2.jpg"
        heading = " Executive Event Technische Dienstverlening"
        description = "Een inspirerend event voor innovatieve Technisch Dienstverleners bij Microsoft"
        btn     = true
        btnText = "AANMELDEN"
        btnURL  = "/contact"
        [[params.banner.flipText]]
            title   = "Inspirerend"
        [[params.banner.flipText]]
            title   = "Interactief"
        [[params.banner.flipText]]
            title   = "Educatief"
        [[params.banner.flipText]]
            title   = ""

# Site Menus

 # Homepage About Section
    [params.about]
        enable  = true
        title   = "Executive Event Technische Dienstverlening"
        content = "<p>Voor dit exclusieve event voor Technische Dienstverleners zijn maximaal 20 plaatsen beschikbaar voor deelname. Ontdek de visie van Microsoft op uw branche en zie een live demo van de slimme oplossingen die u vandaag al kunt inzetten voor meer succes.Verder is er een groepsdiscussie met experts en collega's uit uw branche én u krijgt een rondleiding in het verrassende Technology Center van Microsoft.</p>"
        image   = "/images/about/Innovate-With-Proactive_767x367.png"
        
 # Call to Action
    [params.cta]
        enable  = true
        title   = "Meld u aan voor het event"
        content = "En ontvang de Pylades Factsheet Technische Dienstverlening gratis in uw inbox"
        btnText = "Nu Aanmelden"
        btnURL  = "/contact"