baseURL = "https://stoic-bell-8b8326.netlify.com"
languageCode = "en-us"
title = "IoT Field Service Event"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
   # [[menu.nav]]
    #    name    = "About"
     #   url     = "/about"
      #  weight  = 2
    #[[menu.nav]]
        name    = "Service"
        url     = "/service"
        weight  = 3
    #[[menu.nav]]
        name    = "Gallery"
        url     = "/gallery"
        weight  = 4
    #[[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "/images/slider2.jpg"
        heading = "Pylades Connected Field Service Experience in samenwerking met Microsoft"
        description = "Meld u vandaag nog aan! 23 november 2018 @ Microsoft kantoor te Schiphol"
        btn     = true
        btnText = "AANMELDEN"
        btnURL  = "https://forms.office.com/Pages/ResponsePage.aspx?id=C7l6RXDQ0EGg974_IsqZZlPpQAwKJnNEjMhakYqqkXRURU5BNlkwUlVKUzA0MFJLNU5CSUtHSkZHUy4u"
        [[params.banner.flipText]]
            title   = "Smart Industry"
        [[params.banner.flipText]]
            title   = "Pro Active Field Service"
        [[params.banner.flipText]]
            title   = "Microsoft Dynamics 365"
        [[params.banner.flipText]]
            title   = "Predictive IoT"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "WACHT NIET LANGER"
        content = "Meld u hier aan"
        btnText = "AANMELDEN"
        btnURL  = "https://forms.office.com/Pages/ResponsePage.aspx?id=C7l6RXDQ0EGg974_IsqZZlPpQAwKJnNEjMhakYqqkXRURU5BNlkwUlVKUzA0MFJLNU5CSUtHSkZHUy4u"