baseURL = "https://fieldservice.digital"
languageCode = "nl"
title = "Pylades Connected Field Service Executive Event"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus

# Site Params
[params]
    home = "/"
    logo = "/images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "/images/slider.jpg"
        heading = " Executive Event Technische Dienstverlening"
        description = "Een inspirerend event gericht op innovatie en digitale transformatie in de Technische Dienstverlening"
        btn     = true
        btnText = "AANMELDEN"
        btnURL  = "/contact"
        [[params.banner.flipText]]
            title   = "Industrie 2.0"
        [[params.banner.flipText]]
            title   = "IoT Sensors"
        [[params.banner.flipText]]
            title   = "Hololens"
        [[params.banner.flipText]]
            title   = "Voorspellend Onderhoud"

# Site Menus

 # Homepage About Section
    [params.about]
        enable  = true
        title   = "Executive Event Technische Dienstverlening"
        content = "<p>Voor dit exclusieve event voor Technische Dienstverleners zijn maximaal 20 plaatsen beschikbaar voor deelname. <br> Ontdek de visie van Microsoft op uw branche en zie een live demo van de slimme oplossingen die u vandaag al kunt inzetten voor meer succes.Neem deel aan de round table met experts en collega's uit uw branche én neem deel aan een rondleiding in het hypermoderne Technology Center van Microsoft Nederland.</p>"
        image   = "/images/about/Innovate-With-Proactive_767x367.png"
        
 # Call to Action
    [params.cta]
        enable  = true
        title   = "Meld u aan voor het event"
        content = "En ontvang de Pylades Factsheet Technische Dienstverlening gratis in uw inbox"
        btnText = "Nu Aanmelden"
        btnURL  = "/contact"