baseURL = "https://stoic-bell-8b8326.netlify.com"
languageCode = "en-us"
title = "IoT Field Service Event"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus

# Site Params
[params]
    home = "Home"
    logo = "/images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "/images/slider2.jpg"
        heading = "Connected Field Service"
        description = "Meld u vandaag nog aan DIT IS EEN TEST"
        btn     = true
        btnText = "AANMELDEN"
        btnURL  = "/contact"
        [[params.banner.flipText]]
            title   = "Smart Industry"
        [[params.banner.flipText]]
            title   = "Pro Active Field Service"
        [[params.banner.flipText]]
            title   = "Dynamics 365"
        [[params.banner.flipText]]
            title   = "Predictive IoT"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = ""
        url     = ""
        weight  = 2
    [[menu.nav]]
        name    = "Aanmelden"
        url     = "/contact"
        weight  = 6

 # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT THIS EVENT"
        content = "BlaBlaBlaBlaBla BLAAAAAAAA FIELD SERVICE SHIZZLE"
        image   = "images/about/Innovate-With-Proactive_767x367.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "Nog niet overtuigd?"
        content = "Download meer informatie en blijf op de hoogte of bel ons voor een afspraak"
        btnText = "BEL DAN!"
        btnURL  = "/contact"