baseURL = "https://fieldservice.digital"
languageCode = "nl"
title = "Pylades Connected Field Service Executive Event"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus

# Site Params
[params]
    home = "/"
    logo = "/images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "/images/background3.jpg"
        heading = "Pylades Field Service Executive Event"
        description = "Een inspirerend event voor toekomstgerichte, innovatieve Technisch Dienstverleners in het geheel vernieuwde, hypermoderne en IoT enabled Microsoft kantoor te Schiphol"
        btn     = true
        btnText = "AANMELDEN"
        btnURL  = "/contact"
        [[params.banner.flipText]]
            title   = "Inspirerend"
        [[params.banner.flipText]]
            title   = "Interactief"
        [[params.banner.flipText]]
            title   = "Educatief"
        [[params.banner.flipText]]
            title   = "Exclusief"

# Site Menus

 # Homepage About Section
    [params.about]
        enable  = true
        title   = "Executive Event voor Technische Dienstverleners"
        content = "<p>De opzet van dit exclusieve event voor Technische Dienstverleners is gebaseerd op de principes voor een “executive round table”. Dit houdt in dat er maximaal 20 plaatsen beschikbaar zijn voor deelname.</p><p>Ontdek de visie van Microsoft op uw branche en zie een live demo van de slimme oplossingen die u vandaag al kunt inzetten voor meer succes.</p><p>Verder is er een groepsdiscussie met experts en collega's uit uw branche én u krijgt een rondleiding in het verrassende Technology Center van Microsoft.</p>"
        image   = "/images/about/Innovate-With-Proactive_767x367.png"
        
 # Call to Action
    [params.cta]
        enable  = true
        title   = "Meld u aan voor het event"
        content = "En ontvang de Pylades Factsheet Technische Dienstverlening gratis in uw inbox"
        btnText = "Nu Aanmelden"
        btnURL  = "/contact"